version: '3'

services:
  rsyslog:
    image: croc/rsyslog
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config/client-log.conf:/etc/rsyslog.d/client-log.conf'
      - './logs/:/var/log/servers'
    ports:
      - '5000:5000'
      - '5000:5000/udp'
    restart: always
